# Generated by Django 6.0.4 on 2026-05-04 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_inspection_free_water_volume_1_l_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productreceiptcertificate',
            name='document_hash',
            field=models.CharField(blank=True, help_text='SHA-256 of signed PDF', max_length=64),
        ),
        migrations.AddField(
            model_name='productreceiptcertificate',
            name='is_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productreceiptcertificate',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreceiptcertificate',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sealisolationreport',
            name='document_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='sealisolationreport',
            name='is_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sealisolationreport',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sealisolationreport',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_seal_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shoretankcalculation',
            name='document_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='shoretankcalculation',
            name='is_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shoretankcalculation',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoretankcalculation',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_shore_calcs', to=settings.AUTH_USER_MODEL),
        ),
    ]
