# Generated by Django 6.0.4 on 2026-05-11 01:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_add_digital_signature_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('dip_ticket', 'Dip Ticket'), ('seal_isolation', 'Seal & Isolation Report'), ('product_receipt', 'Product Receipt Certificate'), ('shore_tank', 'Shore Tank Calculation')], max_length=30)),
                ('doc_id', models.PositiveIntegerField()),
                ('doc_number', models.CharField(blank=True, max_length=50)),
                ('vessel_name', models.CharField(blank=True, max_length=200)),
                ('terminal', models.CharField(blank=True, max_length=200)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='VesselReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vessel_name', models.CharField(max_length=200)),
                ('terminal', models.CharField(max_length=200)),
                ('product_name', models.CharField(blank=True, max_length=100)),
                ('discharge_date', models.DateField(default=django.utils.timezone.localdate)),
                ('report_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final')], default='draft', max_length=10)),
                ('dip_ticket_ids', models.JSONField(blank=True, default=list)),
                ('seal_report_ids', models.JSONField(blank=True, default=list)),
                ('shore_calc_ids', models.JSONField(blank=True, default=list)),
                ('cert_ids', models.JSONField(blank=True, default=list)),
                ('total_weight_mt', models.FloatField(default=0)),
                ('total_volume_m3', models.FloatField(default=0)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vessel_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vessel Report',
                'verbose_name_plural': 'Vessel Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
