# Generated by Django 6.0.4 on 2026-05-11 02:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_submission_vesselreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvisionalOuturnReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('vessel_name', models.CharField(max_length=200)),
                ('report_date', models.DateField(default=django.utils.timezone.localdate)),
                ('port', models.CharField(blank=True, max_length=200)),
                ('product', models.CharField(blank=True, max_length=100)),
                ('captain_name', models.CharField(blank=True, max_length=200)),
                ('surveyor_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisional_outturn_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Provisional Outturn Report',
                'verbose_name_plural': 'Provisional Outturn Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProvisionalOuturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.PositiveIntegerField(default=1)),
                ('terminal_name', models.CharField(max_length=200)),
                ('ship_volume_m3', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('ship_weight_mt', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('shore_volume_m3', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('shore_weight_mt', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inspections.provisionalouturnreport')),
            ],
            options={
                'ordering': ['sn'],
            },
        ),
    ]
