# Generated by Django 6.0.4 on 2026-05-11 03:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0005_provisionalouturnreport_provisionalouturnitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('report_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final')], default='draft', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Report',
                'verbose_name_plural': 'Stock Reports',
                'ordering': ['-report_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockReportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.PositiveIntegerField(default=1)),
                ('depot_name', models.CharField(max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('product', models.CharField(max_length=100)),
                ('local_ltrs', models.FloatField(default=0)),
                ('bps_transit_ltrs', models.FloatField(default=0)),
                ('non_bps_transit_ltrs', models.FloatField(default=0)),
                ('mining_ltrs', models.FloatField(default=0)),
                ('transshipment_ltrs', models.FloatField(default=0)),
                ('awaiting_outturn_ltrs', models.FloatField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inspections.stockreport')),
            ],
            options={
                'ordering': ['sn'],
            },
        ),
    ]
