# Generated by Django 6.0.4 on 2026-05-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0006_stockreport_stockreportitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='doc_type',
            field=models.CharField(choices=[('dip_ticket', 'Dip Ticket'), ('seal_isolation', 'Seal & Isolation Report'), ('product_receipt', 'Product Receipt Certificate'), ('shore_tank', 'Shore Tank Calculation'), ('stock_report', 'Stock Report'), ('provisional_outturn', 'Provisional Outturn Report')], max_length=30),
        ),
    ]
