# Generated by Django 6.0.4 on 2026-06-26 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0017_servicerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productreceiptcertificate',
            name='client_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreceiptcertificate',
            name='client_signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prc_client_signed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productreceiptcertificate',
            name='inspector_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreceiptcertificate',
            name='inspector_signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prc_inspector_signed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productreceiptcertificate',
            name='signing_step',
            field=models.CharField(choices=[('draft', 'Draft'), ('inspector_signed', 'Inspector Signed'), ('sent_to_client', 'Sent to Client'), ('client_signed', 'Client Signed'), ('sent_to_inspector', 'Sent Back to Inspector'), ('verified', 'Inspector Verified'), ('submitted', 'Submitted to Admin')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='productreceiptcertificate',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sealisolationreport',
            name='client_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sealisolationreport',
            name='client_signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sir_client_signed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sealisolationreport',
            name='inspector_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sealisolationreport',
            name='inspector_signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sir_inspector_signed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sealisolationreport',
            name='signing_step',
            field=models.CharField(choices=[('draft', 'Draft'), ('inspector_signed', 'Inspector Signed'), ('sent_to_client', 'Sent to Client'), ('client_signed', 'Client Signed'), ('sent_to_inspector', 'Sent Back to Inspector'), ('verified', 'Inspector Verified'), ('submitted', 'Submitted to Admin')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='sealisolationreport',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoretankcalculation',
            name='client_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoretankcalculation',
            name='client_signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stc_client_signed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shoretankcalculation',
            name='inspector_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoretankcalculation',
            name='inspector_signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stc_inspector_signed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shoretankcalculation',
            name='signing_step',
            field=models.CharField(choices=[('draft', 'Draft'), ('inspector_signed', 'Inspector Signed'), ('sent_to_client', 'Sent to Client'), ('client_signed', 'Client Signed'), ('sent_to_inspector', 'Sent Back to Inspector'), ('verified', 'Inspector Verified'), ('submitted', 'Submitted to Admin')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='shoretankcalculation',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
