# Generated by Django 6.0.4 on 2026-06-26 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0018_signing_workflow_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('report_submitted', 'Report Submitted to Admin'), ('report_submitted_client', 'Signed Report Shared with Client')], default='report_submitted', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('doc_type', models.CharField(blank=True, max_length=30)),
                ('doc_id', models.PositiveIntegerField(blank=True, null=True)),
                ('doc_number', models.CharField(blank=True, max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
