# Generated by Codex on 2026-06-27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0020_add_client_company_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(
                choices=[
                    ('ready_to_submit', 'Document Ready to Submit'),
                    ('report_submitted', 'Report Submitted to Admin'),
                    ('report_submitted_client', 'Signed Report Shared with Client'),
                ],
                default='report_submitted',
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name='submission',
            name='doc_type',
            field=models.CharField(
                choices=[
                    ('dip_ticket', 'Dip Ticket'),
                    ('seal_isolation', 'Seal & Isolation Report'),
                    ('product_receipt', 'Product Receipt Certificate'),
                    ('shore_tank', 'Shore Tank Calculation'),
                    ('sampling_form', 'Sampling Form'),
                    ('stock_report', 'Stock Report'),
                    ('provisional_outturn', 'Provisional Outturn Report'),
                ],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name='samplingform',
            name='client_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samplingform',
            name='client_signed_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='sampling_captain_signed',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='samplingform',
            name='document_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='samplingform',
            name='inspector_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samplingform',
            name='inspector_signed_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='sampling_inspector_signed',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='samplingform',
            name='is_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='samplingform',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samplingform',
            name='signed_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='signed_sampling_forms',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='samplingform',
            name='signing_step',
            field=models.CharField(
                choices=[
                    ('draft', 'Draft'),
                    ('inspector_signed', 'Inspector Signed'),
                    ('sent_to_client', 'Sent to Vessel Captain'),
                    ('client_signed', 'Vessel Captain Signed'),
                    ('sent_to_inspector', 'Sent Back to Inspector'),
                    ('verified', 'Inspector Verified'),
                    ('submitted', 'Submitted to Admin'),
                ],
                default='draft',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='samplingform',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
