# Generated by Django 4.2.30 on 2026-07-01 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0023_sr_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspection',
            old_name='supervisor',
            new_name='approved_by',
        ),
        migrations.RenameField(
            model_name='rosterassignment',
            old_name='supervisor',
            new_name='created_by_admin',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ready_to_submit', 'Document Ready to Submit'), ('report_submitted', 'Report Submitted to Admin'), ('report_submitted_client', 'Signed Report Shared with Client'), ('sr_message', 'Service Request Message')], default='report_submitted', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('inspector', 'Inspector'), ('terminal_representative', 'Terminal Representative'), ('admin', 'Admin')], default='inspector', max_length=30),
        ),
    ]
