# Generated by Django 6.0.4 on 2026-04-30 23:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import inspections.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank_id', models.CharField(max_length=50, unique=True)),
                ('tank_name', models.CharField(max_length=100)),
                ('product_type', models.CharField(choices=[('crude_oil', 'Crude Oil'), ('fuel_oil', 'Fuel Oil'), ('diesel', 'Diesel'), ('gasoline', 'Gasoline'), ('water', 'Water'), ('other', 'Other')], max_length=20)),
                ('capacity', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('location', models.CharField(max_length=200)),
                ('height', models.FloatField(help_text='Tank height in meters', validators=[django.core.validators.MinValueValidator(0)])),
                ('diameter', models.FloatField(help_text='Tank diameter in meters', validators=[django.core.validators.MinValueValidator(0)])),
                ('calibration_chart', models.FileField(blank=True, null=True, upload_to='calibration_charts/')),
                ('last_calibrated', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tank',
                'verbose_name_plural': 'Tanks',
                'ordering': ['tank_id'],
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dip_reading', models.FloatField(help_text='Dip reading in cm/meters', validators=[django.core.validators.MinValueValidator(0)])),
                ('temperature', models.FloatField(help_text='Temperature in Celsius', validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(150)])),
                ('water_level', models.FloatField(default=0, help_text='Water level in cm', validators=[django.core.validators.MinValueValidator(0)])),
                ('observations', models.TextField(blank=True)),
                ('tank_condition', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('inspection_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections_created', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections_approved', to=settings.AUTH_USER_MODEL)),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='inspections.tank')),
            ],
            options={
                'verbose_name': 'Inspection',
                'verbose_name_plural': 'Inspections',
                'ordering': ['-inspection_date'],
            },
        ),
        migrations.CreateModel(
            name='InspectionCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_volume', models.FloatField(help_text='Gross volume in barrels/liters', validators=[django.core.validators.MinValueValidator(0)])),
                ('water_volume', models.FloatField(default=0, help_text='Water volume', validators=[django.core.validators.MinValueValidator(0)])),
                ('net_volume', models.FloatField(help_text='Net volume (gross - water)', validators=[django.core.validators.MinValueValidator(0)])),
                ('reference_temperature', models.FloatField(default=15, help_text='Reference temperature (°C)')),
                ('temperature_correction_factor', models.FloatField(default=1.0)),
                ('corrected_volume', models.FloatField(help_text='Temperature corrected volume', validators=[django.core.validators.MinValueValidator(0)])),
                ('product_density', models.FloatField(default=0.85, help_text='Density in g/cm³', validators=[django.core.validators.MinValueValidator(0.5)])),
                ('density_correction_factor', models.FloatField(default=1.0)),
                ('net_standard_volume', models.FloatField(help_text='NSV at standard conditions', validators=[django.core.validators.MinValueValidator(0)])),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calculation', to='inspections.inspection')),
            ],
            options={
                'verbose_name': 'Inspection Calculation',
                'verbose_name_plural': 'Inspection Calculations',
            },
        ),
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('dip_ticket', 'Dip Ticket'), ('inspection_report', 'Inspection Report'), ('daily_summary', 'Daily Summary'), ('monthly_summary', 'Monthly Summary')], max_length=20)),
                ('report_file', models.FileField(upload_to='reports/')),
                ('report_data', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='inspections.inspection')),
            ],
            options={
                'verbose_name': 'Inspection Report',
                'verbose_name_plural': 'Inspection Reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Isolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valve_id', models.CharField(max_length=50)),
                ('valve_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('unknown', 'Unknown')], default='closed', max_length=20)),
                ('pipeline_name', models.CharField(blank=True, max_length=100)),
                ('is_isolated', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isolations', to='inspections.inspection')),
            ],
            options={
                'verbose_name': 'Isolation',
                'verbose_name_plural': 'Isolations',
                'ordering': ['valve_id'],
            },
        ),
        migrations.CreateModel(
            name='ProductReceiptCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('vessel_name', models.CharField(max_length=200)),
                ('terminal', models.CharField(max_length=200)),
                ('receipt_date', models.DateField(default=django.utils.timezone.localdate)),
                ('receipt_time', models.TimeField(default=inspections.models.default_receipt_time)),
                ('quantity_received_through_inlet_flowmeters', models.FloatField(default=0, help_text='Quantity received through inlet flowmeters in liters', validators=[django.core.validators.MinValueValidator(0)])),
                ('terminal_representative_name', models.CharField(max_length=200)),
                ('terminal_representative_signature', models.CharField(blank=True, max_length=200)),
                ('pbpa_inspector_name', models.CharField(blank=True, max_length=200)),
                ('pbpa_inspector_signature', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued')], default='draft', max_length=20)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_receipt_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Receipt Certificate',
                'verbose_name_plural': 'Product Receipt Certificates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Seal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seal_number', models.CharField(max_length=50)),
                ('seal_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('intact', 'Intact'), ('damaged', 'Damaged'), ('missing', 'Missing')], default='intact', max_length=20)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seals', to='inspections.inspection')),
            ],
            options={
                'verbose_name': 'Seal',
                'verbose_name_plural': 'Seals',
                'ordering': ['seal_number'],
            },
        ),
        migrations.CreateModel(
            name='ProductReceiptCertificateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank_no', models.CharField(blank=True, max_length=50)),
                ('product_name', models.CharField(max_length=100)),
                ('weight_tonnage', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('volume_liters', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inspections.productreceiptcertificate')),
                ('tank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_certificate_items', to='inspections.tank')),
            ],
            options={
                'verbose_name': 'Product Receipt Certificate Item',
                'verbose_name_plural': 'Product Receipt Certificate Items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('inspector', 'Inspector'), ('supervisor', 'Supervisor'), ('admin', 'Admin')], default='inspector', max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['tank', '-inspection_date'], name='inspections_tank_id_cf4a2a_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['status'], name='inspections_status_094ca4_idx'),
        ),
    ]
