# Generated by Django 6.0.4 on 2026-05-01 00:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import inspections.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='free_water_volume_1_l',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='inspection',
            name='free_water_volume_2_l',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='inspection',
            name='free_water_volume_3_l',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspection_time',
            field=models.TimeField(default=inspections.models.default_receipt_time),
        ),
        migrations.AddField(
            model_name='inspection',
            name='meter_reading_at_20',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='inspection',
            name='meter_reading_mts',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='inspection',
            name='meter_reading_obs',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='inspection',
            name='other_branches_seal_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='inspection',
            name='outlet_valve_seal_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='inspection',
            name='overall_dip_1_mm',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='inspection',
            name='overall_dip_2_mm',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='inspection',
            name='overall_dip_3_mm',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='inspection',
            name='pbpa_inspector_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inspection',
            name='pbpa_inspector_signature',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inspection',
            name='product_dip_1_mm',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='inspection',
            name='product_dip_2_mm',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='inspection',
            name='product_dip_3_mm',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='inspection',
            name='product_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inspection',
            name='product_volume_1_l',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='inspection',
            name='product_volume_2_l',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='inspection',
            name='product_volume_3_l',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='inspection',
            name='sample_temperature_1_c',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='sample_temperature_2_c',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='sample_temperature_3_c',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='specific_gravity_1',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='inspection',
            name='specific_gravity_2',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='inspection',
            name='specific_gravity_3',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='inspection',
            name='tank_temperature_1_c',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='tank_temperature_2_c',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='tank_temperature_3_c',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='terminal',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inspection',
            name='terminal_representative_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inspection',
            name='terminal_representative_signature',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inspection',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='inspection',
            name='vessel_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inspection',
            name='water_valve_seal_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='SealIsolationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('vessel_name', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=100)),
                ('terminal', models.CharField(max_length=200)),
                ('report_date', models.DateField(default=django.utils.timezone.localdate)),
                ('terminal_representative_name', models.CharField(blank=True, max_length=200)),
                ('terminal_representative_signature', models.CharField(blank=True, max_length=200)),
                ('pbpa_inspector_name', models.CharField(blank=True, max_length=200)),
                ('pbpa_inspector_signature', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued')], default='draft', max_length=20)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seal_isolation_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seal and Isolation Report',
                'verbose_name_plural': 'Seal and Isolation Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SealIsolationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('seal_number', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='inspections.sealisolationreport')),
            ],
            options={
                'verbose_name': 'Seal and Isolation Entry',
                'verbose_name_plural': 'Seal and Isolation Entries',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ShoreTankCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('vessel_name', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=100)),
                ('terminal', models.CharField(max_length=200)),
                ('calculation_date', models.DateField(default=django.utils.timezone.localdate)),
                ('vessel_density_kg_m3', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('vessel_temperature_c', models.FloatField(blank=True, null=True)),
                ('vessel_observed_volume_m3', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('vessel_standard_volume_m3', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('vessel_weight_air_mt', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('meter_quantity_m3', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('pbpa_inspector_name', models.CharField(blank=True, max_length=200)),
                ('terminal_representative_name', models.CharField(blank=True, max_length=200)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final')], default='draft', max_length=20)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shore_tank_calculations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shore Tank Calculation',
                'verbose_name_plural': 'Shore Tank Calculations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShoreTankCalculationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank_no', models.CharField(blank=True, max_length=50)),
                ('overall_dip_initial_mm', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('overall_dip_final_mm', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('water_dip_initial_mm', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('water_dip_final_mm', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('product_dip_initial_mm', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('product_dip_final_mm', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('tank_temperature_initial_c', models.FloatField(blank=True, null=True)),
                ('tank_temperature_final_c', models.FloatField(blank=True, null=True)),
                ('sample_temperature_initial_c', models.FloatField(blank=True, null=True)),
                ('sample_temperature_final_c', models.FloatField(blank=True, null=True)),
                ('density_initial_kg_l', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('density_final_kg_l', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('gross_observed_initial_m3', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('gross_observed_final_m3', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('roof_displacement_initial_m3', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('roof_displacement_final_m3', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('water_volume_initial_m3', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('water_volume_final_m3', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('vcf_initial', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('vcf_final', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('wcf_initial', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('wcf_final', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tank_items', to='inspections.shoretankcalculation')),
                ('tank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shore_calculation_items', to='inspections.tank')),
            ],
            options={
                'verbose_name': 'Shore Tank Calculation Item',
                'verbose_name_plural': 'Shore Tank Calculation Items',
                'ordering': ['id'],
            },
        ),
    ]
