# Generated by Django 6.0.4 on 2026-05-16 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0008_update_roster_assignment'),
        ('inspections', '0009_rosterassignment_is_read'),
    ]

    operations = [
    ]
