# Generated by Django 4.2.30 on 2026-06-26 11:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0015_samplingform_vessel_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rosterassignment',
            options={'ordering': ['-week_start_date', '-created_at'], 'verbose_name': 'Roster Assignment', 'verbose_name_plural': 'Roster Assignments'},
        ),
        migrations.AlterField(
            model_name='rosterassignment',
            name='week_start_date',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Monday of the roster week'),
        ),
        migrations.AlterField(
            model_name='samplingform',
            name='sample_container',
            field=models.CharField(blank=True, help_text='e.g. 1L glass bottle', max_length=200),
        ),
    ]
