# Generated by Django 6.0.4 on 2026-06-26 12:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0016_alter_rosterassignment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('operation_type', models.CharField(choices=[('initial_inspection', 'Initial Inspection'), ('line_displacement', 'Line Displacement'), ('provisional_inspection', 'Provisional Inspection'), ('final_inspection', 'Final Inspection')], max_length=30)),
                ('vessel_name', models.CharField(max_length=200)),
                ('terminal', models.CharField(max_length=200)),
                ('product', models.CharField(blank=True, max_length=100)),
                ('requested_date', models.DateField(default=django.utils.timezone.localdate)),
                ('requested_time', models.TimeField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('is_read_admin', models.BooleanField(default=False)),
                ('is_read_inspector', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_service_requests', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Request',
                'verbose_name_plural': 'Service Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
