# Generated by Django 4.2.30 on 2026-06-27 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspections', '0021_sampling_form_signing_workflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('login_failed', 'Failed Login'), ('report_created', 'Report Created'), ('report_updated', 'Report Updated'), ('report_deleted', 'Report Deleted'), ('report_submitted', 'Report Submitted'), ('report_approved', 'Report Approved'), ('report_rejected', 'Report Rejected'), ('password_changed', 'Password Changed'), ('user_created', 'User Created'), ('user_deleted', 'User Deleted'), ('file_uploaded', 'File Uploaded')], max_length=30)),
                ('doc_type', models.CharField(blank=True, max_length=50)),
                ('doc_id', models.PositiveIntegerField(blank=True, null=True)),
                ('doc_number', models.CharField(blank=True, max_length=50)),
                ('detail', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
